# This a modified: https://github.com/actions/starter-workflows/blob/main/ci/cmake-multi-platform.yml
name: CMake on a single platform

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build
      # Build your program with the given configuration
      run: cc ./BUILD.c && ./a.out

    - name: Test
      #working-directory: ${{github.workspace}}
      # Execute tests defined by the CMake configuration.
      #run: chmod -x ./build/retriever && ./build/retriever  --help 
      run: ${{github.workspace}}/build/retriever  --help 

