# 
name: Cppcheck test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

  #  - name: Build
  #    # Build your program with the given configuration
  #    run: sudo apt install dos2unix && cc ./BUILD.c && ./a.out

    - name: Test
      #working-directory: ${{github.workspace}}
      # TODO add an advance search test later
      run: cppcheck src/app.c
   

